# Generated by Django 4.2 on 2023-05-01 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='adresse',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='messages',
            name='kindmsg',
            field=models.CharField(choices=[('true', 'spam'), ('false', 'normal')], max_length=15),
        ),
        migrations.AlterField(
            model_name='messages',
            name='languages',
            field=models.CharField(max_length=20),
        ),
    ]
