# Generated by Django 4.2 on 2023-05-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_messages_adresse_alter_messages_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='kindmsg',
            field=models.CharField(choices=[(True, 'spam'), (False, 'normal')], max_length=15),
        ),
    ]
