# Generated by Django 4.2 on 2023-07-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_messages_receivernumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='spamsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=30)),
                ('message', models.TextField(default='')),
                ('createat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('createat',), 'verbose_name_plural': 'messages'},
        ),
    ]
