# Generated by Django 4.2.5 on 2023-09-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_spamsmessage_alter_messages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
